### ISSUE TITLE
Tutorial 6: aggregating matrix and data frame

### ISSUE THREAD

**Issue by d-paulus** [tm4ss/tm4ss.github.io#1]
Thanks for the very helpful tutorials. I could follow them until tutorial "5 Filtering documents" without a problem using my own data. Within tutorial "6 Topic proportions over time" I receive the following error when executing line 329:

`Error in aggregate.data.frame(as.data.frame(x), ...) : 
  arguments must have same length`

Is it because the 'theta' matrix and the 'by = list(decade = textdata$decade)' arguments don't have the same length?
```
> length(theta)
[1] 2435670
> length(textdata$decade)
[1] 243568
```

Any help is much appreciated.

**Comment by grenwi** [comment]
This certainly seems to cause the error. But, I cannot reproduce it when running alle code from top to line 329. I assume you forgot to execute some command in between? The data objects should look like this:

```
> length(theta)
[1] 4660
> length(textdata$decade)
[1] 233
> dim(theta)
[1] 233  20
```

**Comment by d-paulus** [comment]
Indeed, I missed line 96. Thanks!
