### ISSUE TITLE
Unable to pre-process corpus in Tutorial 4

### ISSUE THREAD

**Issue by smacsween** [tm4ss/tm4ss.github.io#2]
Thanks very much for the very helpful tutorials, I am learning a lot!

@grenwi  Can you help with this please?  I get error msg below.

https://github.com/tm4ss/tm4ss.github.io/blob/ce70b911d47d3e55f1980fcdba426b946de15e46/Tutorial_4_Term_extraction.Rmd#L55

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.list': error in evaluating the argument 'x' in selecting a method for function 'which': Syntax error in regexp pattern. (U_REGEX_RULE_SYNTAX)

**Comment by grenwi** [comment]
I cannot reproduce this. In case you used your own lemma list check whether it contains some special characters which need to be escaped to be parsed as valid regex.
